default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['CS_DATABASE'] %>
  username: <%= ENV['CS_DATABASE_USERNAME'] %>
  password: <%= ENV['CS_DATABASE_PASSWORD'] %>

